_wandb:
    value:
        cli_version: 0.19.7.dev1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7.dev1
            "8":
                - 5
            "12": 0.19.7.dev1
            "13": linux-x86_64
batch_size:
    value: 32
checkpoint_dir:
    value: ./../model_checkpoints/lstm
embeddings_dir:
    value: ./../data/embeddings
hidden_dim:
    value: 128
lr:
    value: 0.001
lstm_layers:
    value: 2
margin:
    value: 0.3
max_epochs:
    value: 50
patience:
    value: 5
resume_if_checkpoint_exists:
    value: true
