wandb_version: 1

batch_size:
  value: 128
checkpoint_dir:
  value: /./../model_checkpoints
embeddings_dir:
  value: ./../data/embeddings
frames:
  value: 882
hidden_dim:
  value: 128
lr:
  value: 0.0008640346273638608
lstm_layers:
  value: 1
margin:
  value: 0.2
max_epochs:
  value: 50
patience:
  value: 10
resume_if_checkpoint_exists:
  value: false
