wandb_version: 1

batch_size:
  value: 16
checkpoint_dir:
  value: /./../model_checkpoints
embeddings_dir:
  value: ./../data/embeddings
frames:
  value: 691
hidden_dim:
  value: 128
lr:
  value: 0.0002048538413116368
lstm_layers:
  value: 3
margin:
  value: 0.3
max_epochs:
  value: 50
patience:
  value: 10
resume_if_checkpoint_exists:
  value: false
