wandb_version: 1

batch_size:
  value: 32
checkpoint_dir:
  value: /./../model_checkpoints
embeddings_dir:
  value: ./../data/embeddings
frames:
  value: 1000
hidden_dim:
  value: 256
lr:
  value: 0.002590448067233339
lstm_layers:
  value: 1
margin:
  value: 0.3
max_epochs:
  value: 50
patience:
  value: 10
resume_if_checkpoint_exists:
  value: false
