wandb_version: 1

batch_size:
  value: 64
checkpoint_dir:
  value: /./../model_checkpoints
embeddings_dir:
  value: ./../data/embeddings
frames:
  value: 685
hidden_dim:
  value: 256
lr:
  value: 0.000265996416309048
lstm_layers:
  value: 1
margin:
  value: 0.2
max_epochs:
  value: 50
patience:
  value: 10
resume_if_checkpoint_exists:
  value: false
