wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.19.7.dev1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1740834303
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 3
      - 14
      - 16
      - 23
      - 37
      4: 3.10.16
      5: 0.19.7.dev1
      8:
      - 5
      13: linux-x86_64
embeddings_dir:
  desc: null
  value: ./../data/embeddings
checkpoint_dir:
  desc: null
  value: ./../model_checkpoints/lstm/
resume_if_checkpoint_exists:
  desc: null
  value: false
batch_size:
  desc: null
  value: 64
num_frames:
  desc: null
  value: 760
hidden_dim:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.0006265058329531033
lstm_layers:
  desc: null
  value: 2
margin:
  desc: null
  value: 0.3
max_epochs:
  desc: null
  value: 50
patience:
  desc: null
  value: 10
frames:
  desc: null
  value: 760
