# sweep_config.yaml
program: train_lstm.py
method: bayes  # or "random" for random search
metric:
  name: val_loss
  goal: minimize

parameters:
  batch_size:
    values: [16, 32, 64, 128]
  lr:
    min: 1e-4
    max: 1e-2
    distribution: log_uniform_values
  margin:
    values: [0.2, 0.3, 0.4]
  hidden_dim:
    values: [64, 128, 256]
  lstm_layers:
    values: [1, 2, 3]
  frames:
    min: 200
    max: 1000
    distribution: int_uniform  # Ensures whole numbers
  max_epochs:
    value: 50
  patience:
    value: 10
  embeddings_dir:
    value: ./../data/embeddings
  checkpoint_dir:
    value: /./../model_checkpoints
  resume_if_checkpoint_exists:
    value: false
