wandb_version: 1

batch_size:
  value: 32
checkpoint_dir:
  value: ./../model_checkpoints/lstm/
embeddings_dir:
  value: ./../data/embeddings
frames:
  value: 325
hidden_dim:
  value: 256
lr:
  value: 0.008079080202906331
lstm_layers:
  value: 2
margin:
  value: 0.2
max_epochs:
  value: 50
patience:
  value: 10
resume_if_checkpoint_exists:
  value: false
