wandb_version: 1

batch_size:
  value: 64
checkpoint_dir:
  value: ./../model_checkpoints/lstm/
embeddings_dir:
  value: ./../data/embeddings
frames:
  value: 373
hidden_dim:
  value: 256
lr:
  value: 0.00848491520265076
lstm_layers:
  value: 2
margin:
  value: 0.2
max_epochs:
  value: 50
patience:
  value: 10
resume_if_checkpoint_exists:
  value: false
